### ISSUE TITLE
HISAT paired data collection error

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#153]
Hi,

I get the following errror using HISAT with a paired data collection.

```
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 858, in prepare
    self.command_line, self.extra_filenames = tool_evaluator.build()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 411, in build
    self.__build_command_line( )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 427, in __build_command_line
    command_line = fill_template( command, context=param_dict )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/util/template.py", line 9, in fill_template
    return str( Template( source=template_text, searchList=[context] ) )
  File "/usr/local/galaxy/galaxy-dist/eggs/Cheetah-2.2.2-py2.7-linux-x86_64-ucs2.egg/Cheetah/Template.py", line 1004, in __str__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1434276434_44_12951.py", line 115, in respond
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/wrappers.py", line 364, in __getattr__
    return self.__element_instances[ key ]
  File "/usr/local/galaxy/galaxy_env/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'forward'

**Comment by bgruening** [comment]
I think this is fixed and I collect updates to hisat in this branch: https://github.com/galaxyproject/tools-devteam/pull/187
