### ISSUE TITLE
Bamtools "Split" produces error

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#186]
repo: 
tools-devteam/suites/suite_bamtools_2_3_0
https://toolshed.g2.bx.psu.edu/view/devteam/bamtools_split/71dd32fb0b0a

produces an error on every dataset tested 7/21/2015 at usegalaxy.org. (not tested on latest cloudman in dev). original dataset sorted. re-sorting does not avoid the problem. one example for testing/resolution:
https://usegalaxy.org/u/jen-bx-galaxy-edu/h/bamtools-split-error 

reported via galaxy-bugs and confirmed

**Comment by bgruening** [comment]
@jennaj there is not much information in this bug report. @natefoo can you look at the server logs?

**Comment by jennaj** [comment]
Still a problem on Main, here are more details.

Only tested on Main, not local or cloud.

Tool: tools-devteam/tool_collections/bamtools/bamtools_split

Fails: all test runs (bowtie & tophat BAMs tested). probably any mapping-result BAM can be used as a test case.

Error: 
```
tool id: toolshed.g2.bx.psu.edu/repos/devteam/bamtools_split/bamSplit/0.0.1
tool version: 0.0.1
job pid or drm id: X.roundup
job tool version:
-----------------------------------------------------------------------------
job command line:
echo "BAM" > /galaxy-repl/main/files/X/X7/dataset_X.dat &&  ln -s "/galaxy-repl/main/files/X/X/dataset_X.dat" "localbam_0.bam" && ln -s "/galaxy-repl/main/files/_metadata_files/X/X/metadata_X.dat" "localbam_0.bam.bai" &&  bamtools split   -mapped   -stub split_bam  -in "localbam_0.bam"
-----------------------------------------------------------------------------
job stderr:

-----------------------------------------------------------------------------
job stdout:

-----------------------------------------------------------------------------
job info:
Unable to finish job
-----------------------------------------------------------------------------
job traceback:
Traceback (most recent call last):
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/runners/__init__.py", line 603, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/galaxy-repl/instances/main/server/lib/galaxy/jobs/__init__.py", line 1308, in finish
    'primary': self.tool.collect_primary_datasets(out_data, self.working_directory, input_ext)
  File "/galaxy-repl/instances/main/server/lib/galaxy/tools/__init__.py", line 2294, in collect_primary_datasets
    return output_collect.collect_primary_datasets( self, output, job_working_directory, input_ext )
  File "/galaxy-repl/instances/main/server/lib/galaxy/tools/parameters/output_collect.py", line 284, in collect_primary_datasets
    primary_data.set_meta()
  File "/galaxy-repl/instances/main/server/lib/galaxy/model/__init__.py", line 1857, in set_meta
    return self.datatype.set_meta( self, **kwd )
  File "/galaxy-repl/instances/main/server/lib/galaxy/datatypes/binary.py", line 315, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/srv/galaxy/main/python/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/srv/galaxy/main/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/srv/galaxy/main/python/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
