### ISSUE TITLE
unable to install cummerbund's dependencies on Main

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#317]
```
tool_shed.galaxy_install.install_manager ERROR 2015-12-21 17:24:01,779 Error installing tool dependency libpng version 1.6.7: Unable to locate required tool shed repository named package_libpng_1_6_7 owned by devteam with revision 3de32cd300a9.
Traceback (most recent call last):
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/install_manager.py", line 203, in install_specified_tool_dependencies
    from_tool_migration_manager=from_tool_migration_manager )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/install_manager.py", line 306, in install_package
    tool_dependency_db_records=None )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 97, in process_tag_set
    tool_dependency_db_records=tool_dependency_db_records )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 519, in process_tag_set
    from_tool_migration_manager=from_tool_migration_manager )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 507, in handle_complex_repository_dependency_for_package
    raise Exception( message )
Exception: Unable to locate required tool shed repository named package_libpng_1_6_7 owned by devteam with revision 3de32cd300a9.
```

```
tool_shed.galaxy_install.install_manager ERROR 2015-12-21 17:26:30,459 Error installing tool dependency freetype version 2.5.2: Unable to locate required tool shed repository named package_freetype_2_5_2 owned by devteam with revision a65217367e4a.
Traceback (most recent call last):
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/install_manager.py", line 203, in install_specified_tool_dependencies
    from_tool_migration_manager=from_tool_migration_manager )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/install_manager.py", line 306, in install_package
    tool_dependency_db_records=None )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 97, in process_tag_set
    tool_dependency_db_records=tool_dependency_db_records )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 519, in process_tag_set
    from_tool_migration_manager=from_tool_migration_manager )
  File "/galaxy-repl/instances/main/server/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 507, in handle_complex_repository_dependency_for_package
    raise Exception( message )
Exception: Unable to locate required tool shed repository named package_freetype_2_5_2 owned by devteam with revision a65217367e4a.
```

**Comment by martenson** [comment]
ping @davebx

**Comment by martenson** [comment]
I wonder how these were even dependencies of cummerbund while installing given that they are not in tool_dependencies.xml

**Comment by abretaud** [comment]
I get a similar error, but with R dependency:
```
tool_shed.galaxy_install.install_manager ERROR 2016-05-09 18:44:45,442 Error installing tool dependency R version 3.1.2: Unable to locate required tool shed repository named package_r_3_1_2 owned by iuc with revision 6e0eee4ea4e1.
Traceback (most recent call last):
  File "/bipaa-hive/galaxy/galaxy-dist/lib/tool_shed/galaxy_install/install_manager.py", line 198, in install_specified_tool_dependencies
    from_tool_migration_manager=from_tool_migration_manager )
  File "/bipaa-hive/galaxy/galaxy-dist/lib/tool_shed/galaxy_install/install_manager.py", line 301, in install_package
    tool_dependency_db_records=None )
  File "/bipaa-hive/galaxy/galaxy-dist/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 97, in process_tag_set
    tool_dependency_db_records=tool_dependency_db_records )
  File "/bipaa-hive/galaxy/galaxy-dist/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 487, in process_tag_set
    from_tool_migration_manager=from_tool_migration_manager )
  File "/bipaa-hive/galaxy/galaxy-dist/lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 475, in handle_complex_repository_dependency_for_package
    raise Exception( message )
Exception: Unable to locate required tool shed repository named package_r_3_1_2 owned by iuc with revision 6e0eee4ea4e1.
tool_shed.util.tool_dependency_util DEBUG 2016-05-09 18:44:45,462 Updating an existing record for version 3.1.2 of tool dependency R for revision 13c270433440 of repository package_cummerbund_2_8_2 by updating the status from Uninstalled to Error.
```
Any clue on how to fix it?

**Comment by nsoranzo** [comment]
@martenson cummerbund depends on `package_r_3_1_2` which in turns depend on `package_libpng_1_6_7` and `package_freetype_2_5_2` (and others), I don't see anything strange there.

**Comment by martenson** [comment]
@jennaj This might still be an issue, since we have v1.0.1 on Main but TS has 2.16.0 already.

**Comment by bernt-matthias** [comment]
This should be solved by https://github.com/galaxyproject/tools-devteam/pull/560
