### ISSUE TITLE
cummeRbund 1.0.1 error

### ISSUE THREAD

**Issue by methylome** [galaxyproject/tools-devteam#340]
I have no clue why the following errors occurred.
- When loading:
galaxy.tools.parameters.basic DEBUG 2016-02-24 04:04:17,191 Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/1.0.1':
Traceback (most recent call last):
  File "/home/galaxy/dev/lib/galaxy/tools/parameters/basic.py", line 879, in get_options
    return eval( self.dynamic_options, self.tool.code_namespace, call_other_values )
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined

- When executing:
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,270 Building dependency shell command for dependency 'CUMMERBUND_SCRIPT_PATH'
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,270 Find dependency CUMMERBUND_SCRIPT_PATH version None
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,299 Resolver tool_shed_packages returned <galaxy.tools.deps.resolvers.galaxy_packages.GalaxyPackageDependency object at 0x7f173c3de990> (isnull? False)
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,300 Building dependency shell command for dependency 'R'
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,300 Find dependency R version 3.1.2
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,301 Resolver tool_shed_packages returned <galaxy.tools.deps.resolvers.galaxy_packages.GalaxyPackageDependency object at 0x7f173c3de090> (isnull? False)
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,301 Building dependency shell command for dependency 'cummeRbund'
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,301 Find dependency cummeRbund version 2.8.2
galaxy.tools.deps DEBUG 2016-02-24 04:04:59,301 Resolver tool_shed_packages returned <galaxy.tools.deps.resolvers.galaxy_packages.GalaxyPackageDependency object at 0x7f173c3dee50> (isnull? False)
galaxy.jobs.runners ERROR 2016-02-24 04:04:59,515 (137) Failure preparing job
Traceback (most recent call last):
  File "/home/galaxy/dev/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    include_work_dir_outputs=include_work_dir_outputs,
  File "/home/galaxy/dev/lib/galaxy/jobs/runners/__init__.py", line 200, in build_command_line
    container=container
  File "/home/galaxy/dev/lib/galaxy/jobs/command_factory.py", line 41, in build_command
    raise Exception("Attempting to run a tool with empty command definition.")
Exception: Attempting to run a tool with empty command definition.

Thanks,
Justin.

**Comment by methylome** [comment]
I'm using 16_01 and think it worked in 15_10.

**Comment by hershbc** [comment]
I'm having the same problem, was it ever resolved?

**Comment by davebx** [comment]
@methylome, @hershbc: I've managed to track down where it is breaking, but I don't have a solution in place yet. I'll keep looking into it, and try to keep you posted on my progress.

**Comment by hershbc** [comment]
Thanks, issue #465 I believe is the same problem, I wrote it a few days ago, before I realized that this post was the same.  So once it works again, that issue will also be resolved.

**Comment by jennaj** [comment]
May also be related: https://github.com/galaxyproject/galaxy/issues/3030 (Heatmap problems with same tool - might be resolved by same fix).

I closed out https://github.com/galaxyproject/tools-devteam/issues/465 as a duplicate, but it can still be referenced for the heatmap issue with this tool.

Thanks for reporting the problem!

**Comment by davebx** [comment]
Any plot type that tries to fetch parameters from the sqlite file is going to be broken.

**Comment by jennaj** [comment]
@davebx missed this comment, sorry. Should this issue have a more specific ticket (could be named what you commented!) then we list out tools (devtools, iuctools, others on main) that have this same issue? Bundle so can be fixed? Or is there another solution/idea? I don't want to lose the root cause of these failures (still get reported often).

**Comment by jennaj** [comment]
@davebx simple ping to find out the current status for the fix. Thanks!

**Comment by efraimculfa** [comment]
hello, I have encountered with the same problem as I tried to use cummeRbund in galaxy. Previously, I had attempted to visualize my data using RStudio but it wouldn't work.
> cuff<-readCufflinks()
> cuff
Following the two commands above, I would get this;

CuffSet instance with:
	 0 samples
	 0 genes
	 0 isoforms
	 0 TSS
	 0 CDS
	 0 promoters
	 0 splicing
	 0 relCDS
Could it be due to some processing problem in one of the tools of Galaxy?
