### ISSUE TITLE
cufflinks 2.2.1 error

### ISSUE THREAD

**Issue by methylome** [galaxyproject/tools-devteam#341]
On galaxy 16_01, cufflinks 2.2.1 failed. I can successfully run cufflinks by running cufflinks in tool_script.sh. I thinks this error is caused in cufflinks_wrapper.py.

cufflinks v2.2.1
cufflinks -q --no-update-check -I 300000 -F 0.100000 -j 0.150000 -p 1 -g /home/galaxy/dev/database/files/000/dataset_26.dat --3-overhang-tolerance 600 --intron-overhang-tolerance 50 -u -b ref.fa /home/galaxy/dev/database/files/000/dataset_433.dat
Error running cufflinks.
could not convert string to float: chr1 processed_transcript    exon    11869   12227   .       +       .       exon_id "ENSE00002234944"; exon_number "1"; gene_biotype "pseudogene"; gene_id "ENSG00000223972"; gene_name "DDX11L1"; gene_source "ensembl_havana"; tr
Command line:
cufflinks -q --no-update-check -I 300000 -F 0.100000 -j 0.150000 -p 1 -g /home/galaxy/dev/database/files/000/dataset_26.dat --3-overhang-tolerance 600 --intron-overhang-tolerance 50 -u -b ref.fa /home/galaxy/dev/database/files/000/dataset_433.dat
[17:19:30] Loading reference annotation.
[17:20:16] Inspecting reads and determining fragment length distribution.
Processed 34518 loci.
Warning: Using default Gaussian distribution due to insufficient paired-end reads in open ranges.  It is recommended that correct parameters (--frag-len-mean and --frag-len-std-dev) be provided.
> Map Properties:
>       Normalized Map Mass: 9679.13
>       Raw Map Mass: 9679.13
>       Number of Multi-Reads: 631 (with 1614 total hits)
>       Fragment Length Distribution: Truncated Gaussian (default)
>                     Default Mean: 200
>                  Default Std Dev: 80
[17:20:43] Assembling transcripts and initializing abundances for multi-read correction.
Processed 34518 loci.
[18:29:40] Loading reference annotation and sequence.
[18:30:47] Learning bias parameters.
Processed 34174 loci.
[18:31:18] Re-estimating abundances with bias and multi-read correction.
Processed 34174 loci.

Traceback (most recent call last):
  File "/home/galaxy/dev/database/job_working_directory/000/128/set_metadata_x7Rm0C.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/home/galaxy/dev/lib/galaxy_ext/metadata/set_metadata.py", line 85, in set_metadata
    datatypes_registry.load_datatypes( root_dir=galaxy_root, config=datatypes_config )
  File "/home/galaxy/dev/lib/galaxy/datatypes/registry.py", line 94, in load_datatypes
    tree = galaxy.util.parse_xml( config )
  File "/home/galaxy/dev/lib/galaxy/util/__init__.py", line 187, in parse_xml
    root = tree.parse( fname, parser=ElementTree.XMLParser( target=DoctypeSafeCallbackTarget() ) )
  File "/opt/rh/python27/root/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/home/galaxy/dev/database/tmp/tmpyfiDMZ'

Thanks,
Justin

**Comment by methylome** [comment]
I had have no problem in 15_10.

**Comment by methylome** [comment]
I think this is a but in galaxy.
