### ISSUE TITLE
Error for Picard CollectInsertSizeMetrics

### ISSUE THREAD

**Issue by raphenya** [galaxyproject/tools-devteam#411]
```
Fatal error: Exit code 1 ()
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms256m
Exception in thread "main" htsjdk.samtools.SAMException: Reference sequence (424) not found in ../../galaxy/tool-data/grch38/seq/grch38.fa
	at htsjdk.samtools.reference.ReferenceSequenceFileWalker.get(ReferenceSequenceFileWalker.java:98)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:110)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

Any ideas how to solve this? I have picard **package_picard_1_136** installed.

**Comment by jennaj** [comment]
Better places to ask questions are Galaxy Biostars or the Galaxy development list. 

 - https://wiki.galaxyproject.org/Support/Biostar
 - https://wiki.galaxyproject.org/MailingLists

That said, the error has to do with the reference genome. The fasta needs to be add/installed and then indexed for Samtools and Picard. Use Data Managers installed from the Main Tool Shed to do this genome set up.

If you need more help, please post a question to one of the above support sites.
