### ISSUE TITLE
Fastq interlacer 1.2.0 and de-interlacer 1.1.1 tools fail with compressed inputs

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#487]
Tools accept `.gz` and `.bz2` compressed input (output from ncbi fastq dump tool), but fail with an error.

**MTS Repos:**

 - https://toolshed.g2.bx.psu.edu/view/devteam/fastq_paired_end_interlacer/effda79f510c
 - https://toolshed.g2.bx.psu.edu/view/devteam/fastq_paired_end_deinterlacer/462abc5618ba

**Test history:**

 - https://usegalaxy.org/u/jen/h/test-fastq-interlacer-de-interlacer

**Error example:**

```
Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/devteam/fastq_paired_end_interlacer/fastq_paired_end_interlacer/1.2.0.

Tool execution generated the following messages:

Traceback (most recent call last):
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/bin/gx-fastq-paired-end-interlacer", line 6, in 
    sys.exit(galaxy_utils.sequence.scripts.fastq_paired_end_interlacer.main())
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/site-packages/galaxy_utils/sequence/scripts/fastq_paired_end_interlacer.py", line 37, in main
    mate2 = mate2_input.get(joiner.get_paired_identifier(mate1))
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/site-packages/galaxy_utils/sequence/fastq.py", line 705, in get
    fastq_read = next(self.reader)
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/site-packages/galaxy_utils/sequence/fastq.py", line 584, in __next__
    fastq_header = self.file.readline()
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/gzip.py", line 296, in _read
    self.fileobj.seek(0, 2)     # Seek to end of file
  File "/galaxy/main/deps/_conda/envs/__galaxy_sequence_utils@1.1.1/lib/python2.7/gzip.py", line 429, in seek
    raise ValueError('Seek from end not supported')
ValueError: Seek from end not supported
```

ping @nsoranzo thank you!

**Comment by nsoranzo** [comment]
The underlying problem is fixed in https://github.com/galaxyproject/sequence_utils/pull/15 .
The next steps are:
1. release v1.1.2 on https://pypi.python.org/pypi/galaxy_sequence_utils
2. update the bioconda package
3. update `fastq_paired_end_deinterlacer`, `fastq_paired_end_interlacer`, `fastq_paired_end_joiner` tools to use galaxy_sequence_utils 1.1.2 and add tests (I've the code ready, just need to open the PR).
