### ISSUE TITLE
Sicer Version 0.0.1 fails for not finding one of the output files during execution

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#498]
The error is reproducible both at Galaxy Main and Galaxy Freiburg.

- https://usegalaxy.org/u/jen/h/sicer-test
- https://galaxy.uni-freiburg.de/u/jenj/h/copy-of-test-history-sicer

**Main**

> Traceback (most recent call last):
> File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 157, in
> if name=="main": main()
> File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 153, in main
> raise e
> IOError: [Errno 2] No such file or directory: '/galaxy-repl/main/jobdir/017/652/17652579/_job_tmp/tmpcLZaF6/input_bed_file-W200-G600-islands-summary'

**Freiburg**

> Traceback (most recent call last):
>   File "/usr/local/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 157, in 
>     if __name__=="__main__": __main__()
>   File "/usr/local/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 153, in __main__
>     raise e
> IOError: [Errno 2] No such file or directory: '/var/tmp/3819266.1.galaxy1.q/tmpmeKwRD/input_bed_file-W200-G600-islands-summary'

Moved from /galaxy repo: https://github.com/galaxyproject/galaxy/issues/3355

**Comment by jennaj** [comment]
A user reported this problem to usegalaxy.org galaxy-bugs last on 7/27/18.

Is there any update about the tool correction? Is SICER still supported?

ping @davebx @MoHeydarian @bgruening

**Comment by jennaj** [comment]
v 0.0.2 works at EU (test in the same history as above). Upgrading ORG to that version should resolve the prior issues.

**Comment by jennaj** [comment]
v 0.0.2 works at EU: https://usegalaxy.eu/u/jenj/h/copy-of-test-history-sicer

Closing this out and sicer update ticket for main
